version: "3.3"
services:

  server:
    build: ./server
    container_name: mern_server
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    networks:
      - mern-network

  client:
    build: ./client
    container_name: mern_client
    restart: always
    ports:
      - "8082:80"  
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:8000/api
    networks:
      - mern-network
      
networks:
  mern-network:
    driver: bridge
